backend:
  name: git-gateway
  branch: main

media_folder: "user_photos"
public_folder: "user_photos"

collections:
  - name: "gallery"
    label: "Project Gallery"
    files:
      - file: "photos.json"
        label: "Manage Gallery Photos"
        name: "photos_list"
        fields:
          - name: "photos"
            label: "Gallery Images (Drag to Reorder)"
            widget: "list"
            field:
              name: "image"
              label: "Upload Photo"
              widget: "image"
              choose_url: false
