[build]
  publish = "."
  command = ""

# Automatically catch Netlify Identity tokens (invites, recoveries) 
# and land them directly inside the admin portal
[[redirects]]
  from = "/*"
  to = "/admin/#/:splat"
  status = 200
  conditions = {Role = ["*"]} # Ensures it applies site-wide for identity actions

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
